// Deterministic standalone Worker build. No network, dependencies, or deployment.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');

function collectContent(dataRoot = path.join(root, 'data')) {
  const entries = {};
  function visit(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a,b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(file);
      else if (entry.name.endsWith('.json')) {
        const key = path.relative(dataRoot, file).split(path.sep).join('/');
        // Parse at build time to reject malformed source; store strings for lazy runtime parsing.
        entries[key] = JSON.stringify(JSON.parse(fs.readFileSync(file, 'utf8')));
      }
    }
  }
  visit(dataRoot);
  return entries;
}

function renderWorker(source = fs.readFileSync(path.join(root, 'worker.js'), 'utf8'), entries = collectContent()) {
  const normalized = source.replace(/\r\n/g, '\n');
  const data = JSON.stringify(entries);
  const digest = crypto.createHash('sha256').update(normalized).update(data).digest('hex');
  return '// GENERATED by scripts/build-worker.cjs. DO NOT EDIT.\n' +
    `// Source/content SHA-256: ${digest}\n` +
    `const STATIC_GAME_JSON = Object.freeze(${data});\n` + normalized;
}

function build({ check = false } = {}) {
  const output = path.join(root, 'dist', 'worker.js');
  const expected = renderWorker();
  if (check) {
    if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== expected) {
      throw new Error('Generated Worker is stale. Run: node scripts/build-worker.cjs');
    }
  } else {
    fs.mkdirSync(path.dirname(output), { recursive: true });
    fs.writeFileSync(output, expected);
  }
  return { file: output, characters: expected.length, sourceFiles: Object.keys(collectContent()).length };
}

module.exports = { collectContent, renderWorker, build };
if (require.main === module) {
  try { console.log(build({ check: process.argv.includes('--check') })); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
